blank_issues_enabled: false
contact_links:
  - name: ❓ General Questions / Support
    url: https://discord.gg/ftsJPFkWTw
    about: "Need help or have a general question? Join our Discord community for support!"
    
issue_templates:
  - name: 🐛 Bug Report
    description: Report a bug or technical issue in Cops & Robbers.
    labels: ["bug", "triage"]
    url: ./bug_report.yml

  - name: 💡 Feature Request
    description: Suggest a new feature, mechanic, or QoL improvement.
    labels: ["enhancement", "suggestion"]
    url: ./feature_request.yml

  - name: ⚖️ Balance Change Request
    description: Request a balance adjustment for weapons, economy, or gameplay.
    labels: ["balance", "gameplay"]
    url: ./balance_request.yml

  - name: 🎭 Roleplay / Gameplay Idea
    description: Share a roleplay event or gameplay enhancement idea.
    labels: ["roleplay", "gameplay"]
    url: ./gameplay_idea.yml

  - name: 🛠 Modding / Plugin Request
    description: Request a custom mod, plugin, or API enhancement.
    labels: ["modding", "enhancement", "plugin request"]
    url: ./mod_request.yml

  - name: 🏎 Server Performance Issue
    description: Report lag, crashes, or server-related issues.
    labels: ["performance", "server"]
    url: ./performance_issue.yml

  - name: 📜 Documentation Issue
    description: Report missing, outdated, or unclear documentation.
    labels: ["documentation"]
    url: ./documentation_issue.yml
