name: Feature Request 💡
description: Suggest a new feature, mechanic, or quality-of-life improvement for Cops & Robbers.
title: "[Feature Request] <Brief Description>"
labels: ["enhancement", "suggestion"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "🚨 **Before submitting, check existing issues to avoid duplicates!** 🚨"

  - type: input
    id: summary
    attributes:
      label: "💡 Feature Summary"
      description: "Provide a short and clear summary of your idea."
      placeholder: "Example: Add a police informant system for roleplay."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "❓ What Problem Does This Solve?"
      description: "Explain why this feature is needed. What issue does it improve?"
      placeholder: "Example: Right now, police don’t have a good way to track organized crime."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: "🚀 Your Proposed Solution"
      description: "Describe how your feature would work and integrate into the game."
      placeholder: "Example: Add an NPC informant system where criminals can pay for information."
    validations:
      required: true

  - type: textarea
    id: gameplay_impact
    attributes:
      label: "🎮 How Would This Impact Gameplay?"
      description: "Describe how this feature affects balance, economy, or roleplay."
      placeholder: "Example: This would add more strategy for both cops and criminals."
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "📂 Feature Category"
      description: "What area of the game does this suggestion affect?"
      multiple: true
      options:
        - "Heists & Criminal Activities"
        - "Police Mechanics & Law Enforcement"
        - "Weapons & Combat"
        - "Vehicles & Chases"
        - "Economy & Shops"
        - "UI / HUD / Notifications"
        - "Server & Performance"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: potential_risks
    attributes:
      label: "⚠️ Potential Downsides or Risks"
      description: "Are there any issues this feature might cause? (Exploits, balance concerns, etc.)"
      placeholder: "Example: Players might abuse the system to get easy police intel."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "📸 Additional Information"
      description: "Mockups, screenshots, references, or anything else relevant."
      placeholder: "Example: Links to similar mechanics in other games, concept images, etc."
    validations:
      required: false
