name: Modding / Plugin Request 🛠
description: Request a new mod, plugin, or API enhancement for Cops & Robbers.
title: "[Mod Request] <Brief Description>"
labels: ["modding", "enhancement", "plugin request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "🚨 **Before submitting, check existing mod/plugin requests to avoid duplicates!** 🚨"

  - type: input
    id: summary
    attributes:
      label: "🛠 Mod / Plugin Name"
      description: "What is the name of the mod or plugin?"
      placeholder: "Example: Custom Police Radio Integration"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: "❓ What Does This Mod / Plugin Do?"
      description: "Explain the function and purpose of this request."
      placeholder: "Example: A police radio system that allows officers to communicate through in-game voice channels."
    validations:
      required: true

  - type: textarea
    id: why_needed
    attributes:
      label: "🚀 Why Is This Needed?"
      description: "How does this mod/plugin improve the game?"
      placeholder: "Example: Enhances police teamwork and adds realism to pursuits."
    validations:
      required: true

  - type: textarea
    id: existing_mods
    attributes:
      label: "🔎 Are There Similar Mods Available?"
      description: "List any existing mods that provide similar functionality."
      placeholder: "Example: FivePD has a built-in radio system, but it's not compatible with our setup."
    validations:
      required: false

  - type: dropdown
    id: compatibility
    attributes:
      label: "📂 Compatibility"
      description: "Which platforms should this mod/plugin support?"
      multiple: true
      options:
        - "FiveM"
        - "RedM"
        - "Standalone Server"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: technical_details
    attributes:
      label: "💻 Technical Notes"
      description: "If applicable, describe any dependencies, API access, or scripting requirements."
      placeholder: "Example: Requires external API integration for radio channels."
    validations:
      required: false

  - type: textarea
    id: additional_info
    attributes:
      label: "📸 Additional Information"
      description: "Mockups, screenshots, references, or anything else helpful."
      placeholder: "Example: Links to similar plugins, images of UI concepts, etc."
    validations:
      required: false
